function [mammal_struct]=mammal_data(mammal_name,csv_file_name)
%This function receives all the needed data and returns the clustered
%mammal tracts (in aligned mammal brain coordinates)
%% 1) Call data
path = 'C:\Users\M\OneDrive - mail.tau.ac.il\project\Rodentia\';
Node_file_name = fullfile(path, 'Brain_nets_mat', sprintf('%s_FinalFinal2.mat', mammal_name));
Seg_file_name = fullfile(path, 'seg', sprintf('%sseg2.mat', mammal_name));
Tract_file_name = fullfile(path, 'tracts', sprintf('%s_Aniso_GS_MD_C_native_Tracts_CSD_clean.mat', mammal_name));

Alignment_file_name = 'Rodentia_affines.mat';
[tracts, node_locs, MRI_mammal_cent_origin_locs, MRI_mammal_cent] = ...
    load_data(Tract_file_name, Node_file_name, Seg_file_name);

%% 2) Matching cent prediction for first and last tract values
[tract_first_value_cent,tract_last_value_cent]=tract_cent_prediction...
    (tracts,node_locs);

%% 3) Tract Alignment (According to the 200 cents)
% Aligned coordinates (in order for all the brains to "face" the same
% direction
[tracts_aligned] = alignment(Alignment_file_name, mammal_name, tracts);
[node_locs_aligned] = alignment(Alignment_file_name, mammal_name, node_locs);

%% 4) Extract csv data
[cent, cent_locs_original, cent_locs_projected, final_cluster_cent_loc,...
    final_cluster] = extract_csv_data(csv_file_name, mammal_name);
%clustered_cent_idx

%% 5) Match tract to cluster
% For tract first value- find cluster by cent index
[tract_first_val_cluster_idx, clustered_tracts_first_val, ...
    tract_first_val_cluster, cent_per_first_val_tract] = cluster_tracts...
    (tract_first_value_cent, cent, final_cluster, tracts_aligned);

% For tract last value- find cluster by cent index
[tract_last_val_cluster_idx, clustered_tracts_last_val, ...
    tract_last_val_cluster, cent_per_last_val_tract] = cluster_tracts...
    (tract_last_value_cent, cent, final_cluster, tracts_aligned);

%% 5) Output arrays:
% For tract first value- create struct
tract_first_value_struct = struct('cluster_idx', tract_first_val_cluster_idx,...
    'clustered_tracts', {clustered_tracts_first_val}, ...
    'tract_cluster', tract_first_val_cluster, ...
    'cent_per_tract', cent_per_first_val_tract);
tract_last_value_struct = struct('cluster_idx', tract_last_val_cluster_idx, ...
    'clustered_tracts', {clustered_tracts_last_val}, ...
    'tract_cluster', tract_last_val_cluster, ...
    'cent_per_tract', cent_per_last_val_tract);
tract_complete_struct = struct('first_cent_idx', tract_first_val_cluster_idx, ...
    'first_cent', tract_first_value_cent, ...
    'last_cent_idx',tract_last_val_cluster_idx, ...
    'last_cent', tract_last_value_cent, ...
    'tract_complete', {tracts_aligned});

mammal_struct = struct( ...
    'name', mammal_name, ...
    'cent_origins', MRI_mammal_cent, ...
    'original_cent_locs', cent_locs_original, ...
    'projected_cent_locs', cent_locs_projected, ...
    'chosen_cents', cent, ...
    'final_cluster_cent_loc', final_cluster_cent_loc, ...
    'aligned_complete_cent', node_locs_aligned, ...
    'first_tract_data', tract_first_value_struct, ...
    'last_tract_data', tract_last_value_struct, ...
    'tract_complete_struct', tract_complete_struct);

end